# Generated by Django 2.2.7 on 2019-11-25 12:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletePC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(default=datetime.datetime(2019, 11, 25, 9, 45, 30, 553016), verbose_name='Data e hora da criação')),
                ('Memory_ram', models.ManyToManyField(related_name='memory_ram', to='products.MemoryRAM')),
            ],
            options={
                'verbose_name': 'Computador Completo',
                'verbose_name_plural': 'Computadores Completos',
            },
        ),
    ]
