# Generated by Django 2.2.7 on 2019-11-25 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='completepc',
            name='information_of_client',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Cliente'),
        ),
        migrations.AddField(
            model_name='completepc',
            name='motherboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motherboard', to='products.Motherboard'),
        ),
        migrations.AddField(
            model_name='completepc',
            name='processor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processor', to='products.Processor'),
        ),
        migrations.AddField(
            model_name='completepc',
            name='video_board',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_board', to='products.VideoBoard'),
        ),
    ]
