# Generated by Django 2.2.7 on 2019-11-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20191123_1349'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completepc',
            name='Memory_ram',
        ),
        migrations.AddField(
            model_name='completepc',
            name='Memory_ram',
            field=models.ManyToManyField(related_name='memory_ram', to='products.MemoryRAM'),
        ),
    ]
