# Generated by Django 2.2.7 on 2019-11-24 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191124_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='completepc',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 24, 14, 11, 5, 857287), verbose_name='Data e hora da criação'),
        ),
    ]
