# Generated by Django 2.2.7 on 2019-11-25 17:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191125_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completepc',
            name='create_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 14, 18, 46, 933961), verbose_name='Data e hora da criação'),
        ),
    ]
