# Generated by Django 2.2.7 on 2019-11-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryRAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Produto')),
                ('available_sizes', models.CharField(choices=[('OPCAO1', '4 GB'), ('OPCAO2', '8 GB'), ('OPCAO3', '16 GB'), ('OPCAO4', '32 GB'), ('OPCAO5', '64 GB')], max_length=20, verbose_name='Tamanhos disponíveis')),
            ],
            options={
                'verbose_name': 'Memória RAM',
                'verbose_name_plural': 'Memória RAM',
            },
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Produto')),
                ('supported_processor', models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD'), ('INTEL E AMD', 'INTEL E AMD')], max_length=255, verbose_name='Processador suportado')),
                ('quantity_slots_ram', models.IntegerField(verbose_name='Quantidade de slots de RAM')),
                ('total_memory_ram_supported', models.CharField(choices=[('OPCAO1', 'Até 16 GB'), ('OPCAO2', 'Até 64 GB')], max_length=10, verbose_name='Total de memórias RAM suportado')),
                ('integrated_video', models.BooleanField(default=True, verbose_name='Vídeo Integrado')),
            ],
            options={
                'verbose_name': 'Placa Mãe',
                'verbose_name_plural': 'Placas Mãe',
            },
        ),
        migrations.CreateModel(
            name='Processor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Produto')),
                ('brand', models.CharField(choices=[('INTEL', 'INTEL'), ('AMD', 'AMD')], max_length=255, verbose_name='Marca')),
            ],
            options={
                'verbose_name': 'Processador',
                'verbose_name_plural': 'Processadores',
            },
        ),
        migrations.CreateModel(
            name='VideoBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255, verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Placa de vídeo',
                'verbose_name_plural': 'Placas de vídeo',
            },
        ),
    ]
