# Generated by Django 2.2.7 on 2019-11-23 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20191122_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memoryram',
            name='available_sizes',
            field=models.CharField(choices=[('4', '4 GB'), ('8', '8 GB'), ('16', '16 GB'), ('32', '32 GB'), ('64', '64 GB')], max_length=20, verbose_name='Tamanhos disponíveis'),
        ),
        migrations.AlterField(
            model_name='motherboard',
            name='total_memory_ram_supported',
            field=models.CharField(choices=[('16', 'Até 16 GB'), ('64', 'Até 64 GB')], max_length=10, verbose_name='Total de memórias RAM suportado'),
        ),
    ]
